% Params are assigned
params = struct('size', [600 600], ...
                    'saveResults', false, ...                    
                    'show', true, ...  
                    'lambdaBlock', 5, ... % Performance-guided parameters
                    'lambdaPixel', 6, ...
                    'nu', 0.7, ...
                    'thetaColor', 3.0, ...
                    'beta', 1.15, ...
                    'gamma', 0.72, ...
                    'Dupdate', 3, ...                    
                    'alpha', 0.05, ... % Application-guided parameters
                    'Dadd', 100, ...
                    'DSdelete', 200, ...
                    'Ddelete', 200, ...                    
                    'M', 20, ... % Other parameters
                    'N', 20, ...
                    'T', 92, ...
                    'CameraStr', 'LS'); 

hierFgDetection('/local/imaged/calibrated/stereocalib-001/', 0, 328, params);