/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sibtra_lms_ManejaTelegramasJNI */

#ifndef _Included_sibtra_lms_ManejaTelegramasJNI
#define _Included_sibtra_lms_ManejaTelegramasJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sibtra_lms_ManejaTelegramasJNI
 * Method:    ConectaPuerto
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_sibtra_lms_ManejaTelegramasJNI_ConectaPuerto
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sibtra_lms_ManejaTelegramasJNI
 * Method:    isInicializado
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sibtra_lms_ManejaTelegramasJNI_isInicializado
  (JNIEnv *, jobject);

/*
 * Class:     sibtra_lms_ManejaTelegramasJNI
 * Method:    setBaudrate
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_sibtra_lms_ManejaTelegramasJNI_setBaudrate
  (JNIEnv *, jobject, jint);

/*
 * Class:     sibtra_lms_ManejaTelegramasJNI
 * Method:    LeeMensaje
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_sibtra_lms_ManejaTelegramasJNI_LeeMensaje
  (JNIEnv *, jobject);

/*
 * Class:     sibtra_lms_ManejaTelegramasJNI
 * Method:    EnviaMensaje
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_sibtra_lms_ManejaTelegramasJNI_EnviaMensaje
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     sibtra_lms_ManejaTelegramasJNI
 * Method:    cierraPuerto
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sibtra_lms_ManejaTelegramasJNI_cierraPuerto
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
