/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sibtra_shm_shmInterface */

#ifndef _Included_sibtra_shm_shmInterface
#define _Included_sibtra_shm_shmInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sibtra_shm_shmInterface
 * Method:    shmSafeGet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sibtra_shm_shmInterface_shmSafeGet
  (JNIEnv *, jobject);

/*
 * Class:     sibtra_shm_shmInterface
 * Method:    shmSafeErase
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sibtra_shm_shmInterface_shmSafeErase
  (JNIEnv *, jobject);

/*
 * Class:     sibtra_shm_shmInterface
 * Method:    shmWriteGPSOrientation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sibtra_shm_shmInterface_shmWriteGPSOrientation
  (JNIEnv *, jobject);

/*
 * Class:     sibtra_shm_shmInterface
 * Method:    shmReadGPSOrientation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sibtra_shm_shmInterface_shmReadGPSOrientation
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
