#ifndef _APPLICATION
#define _APPLICATION

// Do not edit! This file has been automatically generated by CMake
// Framework/Application.h.cmake

#include <Framework/CApplication.h>
#include <Framework/Application_Registration.h>

#define DECL_METHODS\
  void FillPathManager()\
  {\
    SetPath("SRC_DIR", "/home/nestor/gold/apps/cpd");\
    SetPath(CONF_DIR,  "/home/nestor/gold/apps/cpd/INI");\
    SetPath(HWS_DIR,   "/home/nestor/gold/apps/cpd/HWS");\
    SetPath(DATA_DIR,  "/home/nestor/gold/apps/cpd/Data");\
  }

// TODO: Add here other common files for applications

#endif // _APPLICATION
