/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openservo_OsifJNI */

#ifndef _Included_openservo_OsifJNI
#define _Included_openservo_OsifJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     openservo_OsifJNI
 * Method:    OSIF_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_openservo_OsifJNI_OSIF_1init
  (JNIEnv *, jobject);

/*
 * Class:     openservo_OsifJNI
 * Method:    OSIF_deinit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_openservo_OsifJNI_OSIF_1deinit
  (JNIEnv *, jobject);

/*
 * Class:     openservo_OsifJNI
 * Method:    OSIF_get_libversion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_openservo_OsifJNI_OSIF_1get_1libversion
  (JNIEnv *, jobject);

/*
 * Class:     openservo_OsifJNI
 * Method:    OSIF_write_data
 * Signature: (IIB[BIZ)I
 */
JNIEXPORT jint JNICALL Java_openservo_OsifJNI_OSIF_1write_1data
  (JNIEnv *, jobject, jint, jint, jbyte, jbyteArray, jint, jboolean);

/*
 * Class:     openservo_OsifJNI
 * Method:    OSIF_writeonly
 * Signature: (II[BIZ)I
 */
JNIEXPORT jint JNICALL Java_openservo_OsifJNI_OSIF_1writeonly
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jboolean);

/*
 * Class:     openservo_OsifJNI
 * Method:    OSIF_read_data
 * Signature: (IIB[BIZ)I
 */
JNIEXPORT jint JNICALL Java_openservo_OsifJNI_OSIF_1read_1data
  (JNIEnv *, jobject, jint, jint, jbyte, jbyteArray, jint, jboolean);

/*
 * Class:     openservo_OsifJNI
 * Method:    OSIF_readonly
 * Signature: (II[BIZ)I
 */
JNIEXPORT jint JNICALL Java_openservo_OsifJNI_OSIF_1readonly
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jboolean);

/*
 * Class:     openservo_OsifJNI
 * Method:    OSIF_scan
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_openservo_OsifJNI_OSIF_1scan
  (JNIEnv *, jobject, jint);

/*
 * Class:     openservo_OsifJNI
 * Method:    OSIF_probe
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_openservo_OsifJNI_OSIF_1probe
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     openservo_OsifJNI
 * Method:    OSIF_command
 * Signature: (IIB)I
 */
JNIEXPORT jint JNICALL Java_openservo_OsifJNI_OSIF_1command
  (JNIEnv *, jobject, jint, jint, jbyte);

/*
 * Class:     openservo_OsifJNI
 * Method:    OSIF_get_adapter_count
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_openservo_OsifJNI_OSIF_1get_1adapter_1count
  (JNIEnv *, jobject);

/*
 * Class:     openservo_OsifJNI
 * Method:    OSIF_get_adapter_name
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_openservo_OsifJNI_OSIF_1get_1adapter_1name
  (JNIEnv *, jobject, jint);

/*
 * Class:     openservo_OsifJNI
 * Method:    OSIF_io_set_ddr
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_openservo_OsifJNI_OSIF_1io_1set_1ddr
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     openservo_OsifJNI
 * Method:    OSIF_io_set_out
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_openservo_OsifJNI_OSIF_1io_1set_1out
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     openservo_OsifJNI
 * Method:    OSIF_io_get_in
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_openservo_OsifJNI_OSIF_1io_1get_1in
  (JNIEnv *, jobject, jint);

/*
 * Class:     openservo_OsifJNI
 * Method:    OSIF_io_set_out1
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_openservo_OsifJNI_OSIF_1io_1set_1out1
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     openservo_OsifJNI
 * Method:    OSIF_io_get_current
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_openservo_OsifJNI_OSIF_1io_1get_1current
  (JNIEnv *, jobject, jint);

/*
 * Class:     openservo_OsifJNI
 * Method:    OSIF_disable_i2c
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_openservo_OsifJNI_OSIF_1disable_1i2c
  (JNIEnv *, jobject, jint);

/*
 * Class:     openservo_OsifJNI
 * Method:    OSIF_enable_i2c
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_openservo_OsifJNI_OSIF_1enable_1i2c
  (JNIEnv *, jobject, jint);

/*
 * Class:     openservo_OsifJNI
 * Method:    OSIF_set_bitrate
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_openservo_OsifJNI_OSIF_1set_1bitrate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     openservo_OsifJNI
 * Method:    OSIF_set_twbr
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_openservo_OsifJNI_OSIF_1set_1twbr
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
