/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class carrito_media_MediaCanvas */

#ifndef _Included_carrito_media_MediaCanvas
#define _Included_carrito_media_MediaCanvas
#ifdef __cplusplus
extern "C" {
#endif
#undef carrito_media_MediaCanvas_FOCUS_TRAVERSABLE_UNKNOWN
#define carrito_media_MediaCanvas_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef carrito_media_MediaCanvas_FOCUS_TRAVERSABLE_DEFAULT
#define carrito_media_MediaCanvas_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef carrito_media_MediaCanvas_FOCUS_TRAVERSABLE_SET
#define carrito_media_MediaCanvas_FOCUS_TRAVERSABLE_SET 2L
#undef carrito_media_MediaCanvas_TOP_ALIGNMENT
#define carrito_media_MediaCanvas_TOP_ALIGNMENT 0.0f
#undef carrito_media_MediaCanvas_CENTER_ALIGNMENT
#define carrito_media_MediaCanvas_CENTER_ALIGNMENT 0.5f
#undef carrito_media_MediaCanvas_BOTTOM_ALIGNMENT
#define carrito_media_MediaCanvas_BOTTOM_ALIGNMENT 1.0f
#undef carrito_media_MediaCanvas_LEFT_ALIGNMENT
#define carrito_media_MediaCanvas_LEFT_ALIGNMENT 0.0f
#undef carrito_media_MediaCanvas_RIGHT_ALIGNMENT
#define carrito_media_MediaCanvas_RIGHT_ALIGNMENT 1.0f
#undef carrito_media_MediaCanvas_serialVersionUID
#define carrito_media_MediaCanvas_serialVersionUID -7644114512714619750i64
#undef carrito_media_MediaCanvas_serialVersionUID
#define carrito_media_MediaCanvas_serialVersionUID -2284879212465893870i64
/*
 * Class:     carrito_media_MediaCanvas
 * Method:    paint
 * Signature: (Ljava/awt/Graphics;I)V
 */
JNIEXPORT void JNICALL Java_carrito_media_MediaCanvas_paint
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
