/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class carrito_media_Media */

#ifndef _Included_carrito_media_Media
#define _Included_carrito_media_Media
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     carrito_media_Media
 * Method:    _endMC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_carrito_media_Media__1endMC
  (JNIEnv *, jobject);

/*
 * Class:     carrito_media_Media
 * Method:    _getAncho
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_carrito_media_Media__1getAncho
  (JNIEnv *, jobject, jstring);

/*
 * Class:     carrito_media_Media
 * Method:    _getAlto
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_carrito_media_Media__1getAlto
  (JNIEnv *, jobject, jstring);

/*
 * Class:     carrito_media_Media
 * Method:    _getImagen
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_carrito_media_Media__1getImagen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     carrito_media_Media
 * Method:    _saveImagenActual
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_carrito_media_Media__1saveImagenActual
  (JNIEnv *, jobject, jstring);

/*
 * Class:     carrito_media_Media
 * Method:    _cargaLibreria
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_carrito_media_Media__1cargaLibreria
  (JNIEnv *, jobject, jstring);

/*
 * Class:     carrito_media_Media
 * Method:    _creaInstancia
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_carrito_media_Media__1creaInstancia
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     carrito_media_Media
 * Method:    _play
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_carrito_media_Media__1play
  (JNIEnv *, jobject, jint);

/*
 * Class:     carrito_media_Media
 * Method:    _pausa
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_carrito_media_Media__1pausa
  (JNIEnv *, jobject, jint);

/*
 * Class:     carrito_media_Media
 * Method:    _stop
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_carrito_media_Media__1stop
  (JNIEnv *, jobject, jint);

/*
 * Class:     carrito_media_Media
 * Method:    _fullScreen
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_carrito_media_Media__1fullScreen
  (JNIEnv *, jobject, jint);

/*
 * Class:     carrito_media_Media
 * Method:    _getLength
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_carrito_media_Media__1getLength
  (JNIEnv *, jobject, jint);

/*
 * Class:     carrito_media_Media
 * Method:    _clearPlaylist
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_carrito_media_Media__1clearPlaylist
  (JNIEnv *, jobject, jint);

/*
 * Class:     carrito_media_Media
 * Method:    _getPlaylistIndex
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_carrito_media_Media__1getPlaylistIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     carrito_media_Media
 * Method:    _nextPlaylist
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_carrito_media_Media__1nextPlaylist
  (JNIEnv *, jobject, jint);

/*
 * Class:     carrito_media_Media
 * Method:    _lastPlaylist
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_carrito_media_Media__1lastPlaylist
  (JNIEnv *, jobject, jint);

/*
 * Class:     carrito_media_Media
 * Method:    _getPlayListLength
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_carrito_media_Media__1getPlayListLength
  (JNIEnv *, jobject, jint);

/*
 * Class:     carrito_media_Media
 * Method:    _getPos
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_carrito_media_Media__1getPos
  (JNIEnv *, jobject, jint);

/*
 * Class:     carrito_media_Media
 * Method:    _setPos
 * Signature: (IF)Z
 */
JNIEXPORT jboolean JNICALL Java_carrito_media_Media__1setPos
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     carrito_media_Media
 * Method:    _setFaster
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_carrito_media_Media__1setFaster
  (JNIEnv *, jobject, jint);

/*
 * Class:     carrito_media_Media
 * Method:    _setSlower
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_carrito_media_Media__1setSlower
  (JNIEnv *, jobject, jint);

/*
 * Class:     carrito_media_Media
 * Method:    _getTime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_carrito_media_Media__1getTime
  (JNIEnv *, jobject, jint);

/*
 * Class:     carrito_media_Media
 * Method:    _setTime
 * Signature: (IIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_carrito_media_Media__1setTime
  (JNIEnv *, jobject, jint, jint, jboolean);

/*
 * Class:     carrito_media_Media
 * Method:    _getVolume
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_carrito_media_Media__1getVolume
  (JNIEnv *, jobject, jint);

/*
 * Class:     carrito_media_Media
 * Method:    _setVolume
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_carrito_media_Media__1setVolume
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     carrito_media_Media
 * Method:    _setMute
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_carrito_media_Media__1setMute
  (JNIEnv *, jobject, jint);

/*
 * Class:     carrito_media_Media
 * Method:    _eliminaInstancia
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_carrito_media_Media__1eliminaInstancia
  (JNIEnv *, jobject, jint);

/*
 * Class:     carrito_media_Media
 * Method:    _liberaLibreria
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_carrito_media_Media__1liberaLibreria
  (JNIEnv *, jobject);

/*
 * Class:     carrito_media_Media
 * Method:    _listaDispositivos
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_carrito_media_Media__1listaDispositivos
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
