/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_ull_etsii_VLCJavaPanel */

#ifndef _Included_es_ull_etsii_VLCJavaPanel
#define _Included_es_ull_etsii_VLCJavaPanel
#ifdef __cplusplus
extern "C" {
#endif
#undef es_ull_etsii_VLCJavaPanel_FOCUS_TRAVERSABLE_UNKNOWN
#define es_ull_etsii_VLCJavaPanel_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef es_ull_etsii_VLCJavaPanel_FOCUS_TRAVERSABLE_DEFAULT
#define es_ull_etsii_VLCJavaPanel_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef es_ull_etsii_VLCJavaPanel_FOCUS_TRAVERSABLE_SET
#define es_ull_etsii_VLCJavaPanel_FOCUS_TRAVERSABLE_SET 2L
#undef es_ull_etsii_VLCJavaPanel_TOP_ALIGNMENT
#define es_ull_etsii_VLCJavaPanel_TOP_ALIGNMENT 0.0f
#undef es_ull_etsii_VLCJavaPanel_CENTER_ALIGNMENT
#define es_ull_etsii_VLCJavaPanel_CENTER_ALIGNMENT 0.5f
#undef es_ull_etsii_VLCJavaPanel_BOTTOM_ALIGNMENT
#define es_ull_etsii_VLCJavaPanel_BOTTOM_ALIGNMENT 1.0f
#undef es_ull_etsii_VLCJavaPanel_LEFT_ALIGNMENT
#define es_ull_etsii_VLCJavaPanel_LEFT_ALIGNMENT 0.0f
#undef es_ull_etsii_VLCJavaPanel_RIGHT_ALIGNMENT
#define es_ull_etsii_VLCJavaPanel_RIGHT_ALIGNMENT 1.0f
#undef es_ull_etsii_VLCJavaPanel_serialVersionUID
#define es_ull_etsii_VLCJavaPanel_serialVersionUID -7644114512714619750i64
#undef es_ull_etsii_VLCJavaPanel_serialVersionUID
#define es_ull_etsii_VLCJavaPanel_serialVersionUID -2284879212465893870i64
/*
 * Class:     es_ull_etsii_VLCJavaPanel
 * Method:    paint
 * Signature: (Ljava/awt/Graphics;I)V
 */
JNIEXPORT void JNICALL Java_es_ull_etsii_VLCJavaPanel_paint
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
