/*
 * DlgConfiguraOpciones.java
 *
 * Created on 17 de julio de 2007, 12:19
 */

package carrito.server.interfaz.opciones;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

import org.jdesktop.layout.*;
import org.jdesktop.layout.LayoutStyle;
import carrito.configura.*;

/**
 *
 * @author  nestor
 */
public class DlgConfiguraOpciones
    extends JDialog implements MouseListener {

  private Constantes cte = null;
  private boolean inicializado = false;

  /** Creates new form DlgConfiguraOpciones */
  public DlgConfiguraOpciones(Constantes cte) {
    this.cte = cte;
    initComponents();
    cte.openServer();
    chkAvance.setSelected(cte.isCanAvance());
    chkDesfreno.setSelected(cte.isCanDesfreno());
    chkFreno.setSelected(cte.isCanFreno());
    chkFrenoEmergencia.setSelected(cte.isCanFrenoEmergencia());
    chkGiro.setSelected(cte.isCanGiro());
    chkRetroceso.setSelected(cte.isCanRetroceso());
    chkInitDesfreno.setSelected(cte.isCanInitDesfreno());
    chkInitGiro.setSelected(cte.isCanInitVolante());

    btnAceptar.addMouseListener(this);
    btnCancelar.addMouseListener(this);

    Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
    setLocation((d.width - getWidth()) / 2, (d.height - getHeight()) / 2);
    
  }

  /** This method is called from within the constructor to
   * nitialize thei form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    pnlOpciones = new javax.swing.JPanel();
    chkFrenoEmergencia = new javax.swing.JCheckBox();
    chkFreno = new javax.swing.JCheckBox();
    chkDesfreno = new javax.swing.JCheckBox();
    chkRetroceso = new javax.swing.JCheckBox();
    chkAvance = new javax.swing.JCheckBox();
    chkGiro = new javax.swing.JCheckBox();
    chkInitGiro = new javax.swing.JCheckBox();
    chkInitDesfreno = new javax.swing.JCheckBox();
    btnAceptar = new javax.swing.JButton();
    btnCancelar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setTitle("Configuraci\u00f3n del Veh\u00edculo");
    pnlOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(
        "Opciones de Funcionamiento de Veh\u00edculo"));
    pnlOpciones.setName("null");
    chkFrenoEmergencia.setSelected(true);
    chkFrenoEmergencia.setText("Freno de emergencia");
    chkFrenoEmergencia.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,
        0, 0, 0));
    chkFrenoEmergencia.setMargin(new java.awt.Insets(0, 0, 0, 0));

    chkFreno.setSelected(true);
    chkFreno.setText("Frenado");
    chkFreno.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    chkFreno.setMargin(new java.awt.Insets(0, 0, 0, 0));

    chkDesfreno.setSelected(true);
    chkDesfreno.setText("Desfrenado");
    chkDesfreno.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0,
        0));
    chkDesfreno.setMargin(new java.awt.Insets(0, 0, 0, 0));

    chkRetroceso.setSelected(true);
    chkRetroceso.setText("Marcha atr\u00e1s");
    chkRetroceso.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0,
        0));
    chkRetroceso.setMargin(new java.awt.Insets(0, 0, 0, 0));

    chkAvance.setSelected(true);
    chkAvance.setText("Avance");
    chkAvance.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    chkAvance.setMargin(new java.awt.Insets(0, 0, 0, 0));

    chkGiro.setSelected(true);
    chkGiro.setText("Giro");
    chkGiro.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    chkGiro.setMargin(new java.awt.Insets(0, 0, 0, 0));

    chkInitGiro.setSelected(true);
    chkInitGiro.setText("Inicializaci\u00f3n del Volante");
    chkInitGiro.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0,
        0));
    chkInitGiro.setMargin(new java.awt.Insets(0, 0, 0, 0));

    chkInitDesfreno.setSelected(true);
    chkInitDesfreno.setText("Inicializaci\u00f3n del Desfreno");
    chkInitDesfreno.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0,
        0, 0));
    chkInitDesfreno.setMargin(new java.awt.Insets(0, 0, 0, 0));

    org.jdesktop.layout.GroupLayout pnlOpcionesLayout = new org.jdesktop.layout.GroupLayout(pnlOpciones);
    pnlOpciones.setLayout(pnlOpcionesLayout);
    pnlOpcionesLayout.setHorizontalGroup(
        pnlOpcionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(pnlOpcionesLayout.createSequentialGroup()
             .addContainerGap()
             .add(pnlOpcionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                  .add(chkFrenoEmergencia)
                  .add(chkFreno)
                  .add(chkDesfreno)
                  .add(chkAvance)
                  .add(chkRetroceso)
                  .add(chkGiro)
                  .add(chkInitGiro)
                  .add(chkInitDesfreno))
             .addContainerGap(239, Short.MAX_VALUE))
        );
    pnlOpcionesLayout.setVerticalGroup(
        pnlOpcionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(pnlOpcionesLayout.createSequentialGroup()
             .add(chkFrenoEmergencia)
             .addPreferredGap(LayoutStyle.RELATED)
             .add(chkFreno)
             .addPreferredGap(LayoutStyle.RELATED)
             .add(chkDesfreno)
             .addPreferredGap(LayoutStyle.RELATED)
             .add(chkAvance)
             .addPreferredGap(LayoutStyle.RELATED)
             .add(chkRetroceso)
             .addPreferredGap(LayoutStyle.RELATED)
             .add(chkGiro)
             .addPreferredGap(LayoutStyle.RELATED)
             .add(chkInitGiro)
             .addPreferredGap(LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                              Short.MAX_VALUE)
             .add(chkInitDesfreno)
             .addContainerGap())
        );

    btnCancelar.setText("Cancelar");

    btnAceptar.setText("Aceptar");
    btnAceptar.setSelected(true);

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(layout.createSequentialGroup()
             .addContainerGap()
             .add(pnlOpciones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                  org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
             .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
             .addContainerGap(271, Short.MAX_VALUE)
             .add(btnAceptar)
             .addPreferredGap(LayoutStyle.RELATED)
             .add(btnCancelar)
             .addContainerGap())
        );
    layout.setVerticalGroup(
        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(layout.createSequentialGroup()
             .addContainerGap()
             .add(pnlOpciones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                  org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
             .addPreferredGap(LayoutStyle.RELATED)
             .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                  .add(btnCancelar)
                  .add(btnAceptar))
             .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    pack();
  } // </editor-fold>//GEN-END:initComponents

  public void mouseClicked(MouseEvent e) {
    // Se pulsó el botón izquierdo
    if (e.getButton() == MouseEvent.BUTTON1) {
      // Se pulsó Cancelar
      if (e.getSource() == btnCancelar) {
        chkAvance.setSelected(cte.isCanAvance());
        chkDesfreno.setSelected(cte.isCanDesfreno());
        chkFreno.setSelected(cte.isCanFreno());
        chkFrenoEmergencia.setSelected(cte.isCanFrenoEmergencia());
        chkGiro.setSelected(cte.isCanGiro());
        chkRetroceso.setSelected(cte.isCanRetroceso());
        chkInitDesfreno.setSelected(cte.isCanInitDesfreno());
        chkInitGiro.setSelected(cte.isCanInitVolante());

        inicializado = true;
      } // Se pulsó aceptar
      else if (e.getSource() == btnAceptar) {
        cte.setCanAvance(chkAvance.isSelected());
        cte.setCanDesfreno(chkDesfreno.isSelected());
        cte.setCanFreno(chkFreno.isSelected());
        cte.setCanFrenoEmergencia(chkFrenoEmergencia.isSelected());
        cte.setCanGiro(chkGiro.isSelected());
        cte.setCanInitDesfreno(chkInitDesfreno.isSelected());
        cte.setCanInitVolante(chkInitGiro.isSelected());
        cte.setCanRetroceso(chkRetroceso.isSelected());

        // Se guarda en el fichero
        cte.saveServer();

        inicializado = true;
      }
    }
  }

  /**
   * Evento <i>mouseEntered</i>
   * @param e MouseEvent
   */
  public void mouseEntered(MouseEvent e) {}

  /**
   * Evento <i>mouseExited</i>
   * @param e MouseEvent
   */
  public void mouseExited(MouseEvent e) {}

  /**
   * Evento <i>mousePressed</i>
   * @param e MouseEvent
   */
  public void mousePressed(MouseEvent e) {}

  /**
   * Evento <i>mouseReleased</i>
   * @param e MouseEvent
   */
  public void mouseReleased(MouseEvent e) {}

  public boolean isInicializado() {
    return inicializado;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox chkAvance;
  private javax.swing.JCheckBox chkDesfreno;
  private javax.swing.JCheckBox chkFreno;
  private javax.swing.JCheckBox chkFrenoEmergencia;
  private javax.swing.JCheckBox chkGiro;
  private javax.swing.JCheckBox chkInitDesfreno;
  private javax.swing.JCheckBox chkInitGiro;
  private javax.swing.JCheckBox chkRetroceso;
  private javax.swing.JButton btnAceptar;
  private javax.swing.JButton btnCancelar;
  private javax.swing.JPanel pnlOpciones;
  // End of variables declaration//GEN-END:variables

}
